[pytest]
markers =
    ui: Тесты, проверяющие пользовательский интерфейс (Selenium)
    api: Тесты, проверяющие программный интерфейс (Requests)
addopts = --clean-alluredir --alluredir=allure-results
pythonpath = .